#!/bin/bash
#
# TypeScript Type Generation Script
#
# Implements Task P0-35: Enforce Chart Schema with Pydantic → OpenAPI → TypeScript
#
# This script:
# 1. Fetches OpenAPI spec from FastAPI backend
# 2. Generates TypeScript types using openapi-typescript
# 3. Extracts chart types into separate file for convenience
#
# Usage:
#   ./scripts/generate-types.sh
#
# Prerequisites:
#   - Backend server running on http://localhost:8000
#   - openapi-typescript installed (npm install -D openapi-typescript)
#

set -e  # Exit on error

# Configuration
API_URL="${API_URL:-http://localhost:8000}"
OPENAPI_URL="${API_URL}/openapi.json"
OUTPUT_DIR="src/types"
TEMP_FILE="openapi.json"

echo "🔧 TypeScript Type Generation"
echo "=============================="
echo ""

# Check if backend is running
echo "📡 Checking backend availability..."
if ! curl -s --connect-timeout 5 "${API_URL}/health" > /dev/null 2>&1; then
    echo "❌ Backend not available at ${API_URL}"
    echo ""
    echo "Please start the backend server:"
    echo "  cd ../python"
    echo "  uvicorn src.server.main:app --reload"
    echo ""
    exit 1
fi
echo "✅ Backend is running"
echo ""

# Fetch OpenAPI spec
echo "📥 Fetching OpenAPI specification..."
if ! curl -s "${OPENAPI_URL}" -o "${TEMP_FILE}"; then
    echo "❌ Failed to fetch OpenAPI spec from ${OPENAPI_URL}"
    exit 1
fi

# Validate JSON
if ! jq empty "${TEMP_FILE}" 2>/dev/null; then
    echo "❌ Invalid JSON in OpenAPI spec"
    rm -f "${TEMP_FILE}"
    exit 1
fi

echo "✅ OpenAPI spec downloaded ($(wc -c < ${TEMP_FILE}) bytes)"
echo ""

# Create output directory
mkdir -p "${OUTPUT_DIR}"

# Generate TypeScript types
echo "🔨 Generating TypeScript types..."
if ! npx openapi-typescript "${TEMP_FILE}" --output "${OUTPUT_DIR}/api.generated.ts" 2>&1; then
    echo "❌ Failed to generate TypeScript types"
    rm -f "${TEMP_FILE}"
    exit 1
fi
echo "✅ Generated ${OUTPUT_DIR}/api.generated.ts"
echo ""

# Extract chart types for convenience
echo "📦 Extracting chart types..."
cat > "${OUTPUT_DIR}/charts.generated.ts" << 'EOF'
/**
 * Chart Type Definitions
 * 
 * Auto-generated from backend Pydantic schemas
 * Generated by: scripts/generate-types.sh
 * 
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 * 
 * To regenerate:
 *   npm run generate:types
 */

import { components } from './api.generated';

// Chart data point types
export type ChartDataPoint = components['schemas']['ChartDataPoint'];
export type PieChartDataPoint = components['schemas']['PieChartDataPoint'];

// Chart configuration types
export type LineChartConfig = components['schemas']['LineChartConfig'];
export type BarChartConfig = components['schemas']['BarChartConfig'];
export type PieChartConfig = components['schemas']['PieChartConfig'];
export type AreaChartConfig = components['schemas']['AreaChartConfig'];

// Union type for all chart configurations
export type ChartConfig =
  | LineChartConfig
  | BarChartConfig
  | PieChartConfig
  | AreaChartConfig;

// Metric card type
export type MetricCard = components['schemas']['MetricCard'];

// Type guards for runtime type checking
export function isLineChart(config: ChartConfig): config is LineChartConfig {
  return config.type === 'line';
}

export function isBarChart(config: ChartConfig): config is BarChartConfig {
  return config.type === 'bar';
}

export function isPieChart(config: ChartConfig): config is PieChartConfig {
  return config.type === 'pie';
}

export function isAreaChart(config: ChartConfig): config is AreaChartConfig {
  return config.type === 'area';
}

// Helper function to validate chart type
export function getChartType(config: ChartConfig): 'line' | 'bar' | 'pie' | 'area' {
  return config.type;
}
EOF

echo "✅ Generated ${OUTPUT_DIR}/charts.generated.ts"
echo ""

# Clean up
rm -f "${TEMP_FILE}"

# Statistics
echo "📊 Type Generation Statistics"
echo "=============================="
echo "API types: $(grep -c 'export type' ${OUTPUT_DIR}/api.generated.ts || echo 0)"
echo "Chart types: $(grep -c 'export type' ${OUTPUT_DIR}/charts.generated.ts || echo 0)"
echo ""

echo "✅ Type generation complete!"
echo ""
echo "Types are available at:"
echo "  - ${OUTPUT_DIR}/api.generated.ts (full API types)"
echo "  - ${OUTPUT_DIR}/charts.generated.ts (chart-specific types)"
echo ""
echo "Usage in components:"
echo "  import { ChartConfig, isLineChart } from '@/types/charts.generated';"
echo ""

