#!/usr/bin/env node
/**
 * TypeScript Type Generation Script
 *
 * Implements Task P0-35: Enforce Chart Schema with Pydantic → OpenAPI → TypeScript
 *
 * This script:
 * 1. Fetches OpenAPI spec from FastAPI backend
 * 2. Generates TypeScript types using openapi-typescript
 * 3. Extracts chart types into separate file for convenience
 *
 * Usage:
 *   node scripts/generate-types.js
 *   npm run generate:types
 *
 * Prerequisites:
 *   - Backend server running on http://localhost:8000
 *   - openapi-typescript installed (npm install -D openapi-typescript)
 */

const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');
const { execSync } = require('child_process');

// Configuration
const API_URL = process.env.API_URL || 'http://localhost:8000';
const OPENAPI_URL = `${API_URL}/openapi.json`;
const OUTPUT_DIR = path.join(__dirname, '..', 'src', 'types');
const TEMP_FILE = path.join(__dirname, 'openapi.json');

console.log('🔧 TypeScript Type Generation');
console.log('==============================');
console.log('');

// Helper function to download file
function downloadFile(url, dest) {
  return new Promise((resolve, reject) => {
    const protocol = url.startsWith('https') ? https : http;
    const file = fs.createWriteStream(dest);
    
    protocol.get(url, (response) => {
      if (response.statusCode !== 200) {
        reject(new Error(`Failed to download: ${response.statusCode}`));
        return;
      }
      
      response.pipe(file);
      file.on('finish', () => {
        file.close();
        resolve();
      });
    }).on('error', (err) => {
      fs.unlink(dest, () => {});
      reject(err);
    });
  });
}

// Helper function to check if backend is running
async function checkBackend() {
  return new Promise((resolve) => {
    const protocol = API_URL.startsWith('https') ? https : http;
    const healthUrl = `${API_URL}/health`;
    
    protocol.get(healthUrl, { timeout: 5000 }, (response) => {
      resolve(response.statusCode === 200);
    }).on('error', () => {
      resolve(false);
    }).on('timeout', () => {
      resolve(false);
    });
  });
}

async function main() {
  try {
    // Check if backend is running
    console.log('📡 Checking backend availability...');
    const isBackendRunning = await checkBackend();
    
    if (!isBackendRunning) {
      console.error('❌ Backend not available at', API_URL);
      console.log('');
      console.log('Please start the backend server:');
      console.log('  cd ../python');
      console.log('  uvicorn src.server.main:app --reload');
      console.log('');
      process.exit(1);
    }
    console.log('✅ Backend is running');
    console.log('');

    // Fetch OpenAPI spec
    console.log('📥 Fetching OpenAPI specification...');
    await downloadFile(OPENAPI_URL, TEMP_FILE);
    
    const stats = fs.statSync(TEMP_FILE);
    console.log(`✅ OpenAPI spec downloaded (${stats.size} bytes)`);
    console.log('');

    // Validate JSON
    try {
      JSON.parse(fs.readFileSync(TEMP_FILE, 'utf8'));
    } catch (err) {
      console.error('❌ Invalid JSON in OpenAPI spec');
      fs.unlinkSync(TEMP_FILE);
      process.exit(1);
    }

    // Create output directory
    if (!fs.existsSync(OUTPUT_DIR)) {
      fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    // Generate TypeScript types
    console.log('🔨 Generating TypeScript types...');
    try {
      execSync(
        `npx openapi-typescript "${TEMP_FILE}" --output "${path.join(OUTPUT_DIR, 'api.generated.ts')}"`,
        { stdio: 'inherit' }
      );
      console.log(`✅ Generated ${path.join(OUTPUT_DIR, 'api.generated.ts')}`);
      console.log('');
    } catch (err) {
      console.error('❌ Failed to generate TypeScript types');
      console.error(err.message);
      fs.unlinkSync(TEMP_FILE);
      process.exit(1);
    }

    // Extract chart types for convenience
    console.log('📦 Extracting chart types...');
    const chartTypesContent = `/**
 * Chart Type Definitions
 * 
 * Auto-generated from backend Pydantic schemas
 * Generated by: scripts/generate-types.js
 * 
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 * 
 * To regenerate:
 *   npm run generate:types
 */

import { components } from './api.generated';

// Chart data point types
export type ChartDataPoint = components['schemas']['ChartDataPoint'];
export type PieChartDataPoint = components['schemas']['PieChartDataPoint'];

// Chart configuration types
export type LineChartConfig = components['schemas']['LineChartConfig'];
export type BarChartConfig = components['schemas']['BarChartConfig'];
export type PieChartConfig = components['schemas']['PieChartConfig'];
export type AreaChartConfig = components['schemas']['AreaChartConfig'];

// Union type for all chart configurations
export type ChartConfig =
  | LineChartConfig
  | BarChartConfig
  | PieChartConfig
  | AreaChartConfig;

// Metric card type
export type MetricCard = components['schemas']['MetricCard'];

// Type guards for runtime type checking
export function isLineChart(config: ChartConfig): config is LineChartConfig {
  return config.type === 'line';
}

export function isBarChart(config: ChartConfig): config is BarChartConfig {
  return config.type === 'bar';
}

export function isPieChart(config: ChartConfig): config is PieChartConfig {
  return config.type === 'pie';
}

export function isAreaChart(config: ChartConfig): config is AreaChartConfig {
  return config.type === 'area';
}

// Helper function to validate chart type
export function getChartType(config: ChartConfig): 'line' | 'bar' | 'pie' | 'area' {
  return config.type;
}
`;

    fs.writeFileSync(
      path.join(OUTPUT_DIR, 'charts.generated.ts'),
      chartTypesContent,
      'utf8'
    );
    console.log(`✅ Generated ${path.join(OUTPUT_DIR, 'charts.generated.ts')}`);
    console.log('');

    // Clean up
    fs.unlinkSync(TEMP_FILE);

    // Statistics
    const apiTypes = fs.readFileSync(path.join(OUTPUT_DIR, 'api.generated.ts'), 'utf8');
    const chartTypes = fs.readFileSync(path.join(OUTPUT_DIR, 'charts.generated.ts'), 'utf8');
    
    console.log('📊 Type Generation Statistics');
    console.log('==============================');
    console.log('API types:', (apiTypes.match(/export type/g) || []).length);
    console.log('Chart types:', (chartTypes.match(/export type/g) || []).length);
    console.log('');

    console.log('✅ Type generation complete!');
    console.log('');
    console.log('Types are available at:');
    console.log(`  - ${path.join(OUTPUT_DIR, 'api.generated.ts')} (full API types)`);
    console.log(`  - ${path.join(OUTPUT_DIR, 'charts.generated.ts')} (chart-specific types)`);
    console.log('');
    console.log('Usage in components:');
    console.log("  import { ChartConfig, isLineChart } from '@/types/charts.generated';");
    console.log('');
  } catch (err) {
    console.error('❌ Error:', err.message);
    if (fs.existsSync(TEMP_FILE)) {
      fs.unlinkSync(TEMP_FILE);
    }
    process.exit(1);
  }
}

main();

